services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart:
      always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
